# Generated by Django 4.2.9 on 2024-10-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventas_descuento_ventas_impuestos_ventas_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='impuestos',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
