# Generated by Django 4.2.9 on 2024-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimiento',
            name='nombre',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salidas', 'Salida'), ('ajuste', 'Ajuste'), ('tranferencia', 'Tranferencia')], max_length=100, unique=True),
        ),
    ]
